version: '2'
networks:
  myshop:
    driver: bridge
services:
  proxy:
    image: hjgraca/myshopproxy:latest
    ports: ["8080:80"]
    networks:
      - myshop
  products:
    image: hjgraca/products-api:v1
    networks:
      - myshop
  ratings:
    image: hjgraca/ratings-api:v1
    networks:
      - myshop
  recommendations:
    image: hjgraca/recommendations-api:v1
    networks:
      - myshop
  shop:
    image: hjgraca/shopfront:v1
    networks:
      - myshop
    environment:
      - SHOP_PRODUCTS_API_URL=/api/products
      - SHOP_RATINGS_API_URL=/api/ratings
      - SHOP_RECOMMANDATIONS_API_URL=/api/recommendations