version: '2'
services:
  proxy:
    image: hjgraca/myshopproxy:latest
    ports: ["8080:80"]
  products:
    image: hjgraca/products-api:v2
  ratings:
    image: hjgraca/ratings-api:v1
  recommendations:
    image: hjgraca/recommendations-api:v1
  shop:
    image: hjgraca/shopfront:v1
    environment:
      - SHOP_PRODUCTS_API_URL=/api/products
      - SHOP_RATINGS_API_URL=/api/ratings
      - SHOP_RECOMMANDATIONS_API_URL=/api/recommendations